#启动: nohup java  -Dspring.profiles.active=dev -jar synchronius-1.0.jar >  log.erp 2>&1 &

server:
  port: 8092
  compression:
    enabled: true
  connection-timeout: 3000

dubbo:
  name: dubboBoot
  zookeeper: zookeeper://127.0.0.1:2181

